// Auto-generated by gasnuki
// Do NOT edit this file manually.
export interface ServerScripts {
  myFunction(name: string): string;
}

// Auto-generated Types for GoogleAppsScript in client-side code

type RemoveReturnType<T> = {
  [P in keyof T]: T[P] extends (...args: infer A) => any
    ? (...args: A) => void
    : T[P];
};

type _AppsScriptRun = RemoveReturnType<ServerScripts> & {
  withSuccessHandler: <T = string | number | boolean | undefined, U = any>(
    callback: (returnValues: T, userObject?: U) => void,
  ) => _AppsScriptRun;
  withFailureHandler: <U = any>(
    callback: (error: Error, userObject?: U) => void,
  ) => _AppsScriptRun;
  withUserObject: <U = any>(userObject: U) => _AppsScriptRun;
};

type _AppsScriptHistoryFunction = (
  stateObject: object,
  params: object,
  hash: string,
) => void;

interface _WebAppLovacationType {
  hash: string;
  parameter: Record<string, string>;
  parameters: Record<string, string[]>;
}

export declare interface GoogleClientSideApi {
  script: {
    run: _AppsScriptRun;
    url: {
      getLocation: (callback: (location: _WebAppLovacationType) => void) => void;
    };
    history: {
      push: _AppsScriptHistoryFunction;
      replace: _AppsScriptHistoryFunction;
      setChangeHandler: (
        callback: (e: { state: object; location: _WebAppLovacationType }) => void
      ) => void;
    }
  };
}

declare global {
  const google: GoogleClientSideApi;
}
