name: Check Package Version on every monday and pushing on main branch

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check npm packages version
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.1
    
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
    
      - name: Check for outdated packages and save result
        id: outdated-check
        shell: bash
        run: |
          echo "--- Running 'pnpm outdated -r' for debugging ---"
          pnpm outdated -r || true
          echo "-----------------------------------------------"

          echo "--- Capturing output of 'pnpm outdated --format json -r' ---"
          pnpm outdated --format json -r > outdated.json 2> stderr.log
          exit_code=$?

          echo "Exit Code: $exit_code"
          echo "--- Stderr from pnpm outdated ---"
          cat stderr.log
          echo "-----------------------------------"
          echo "--- Stdout (outdated.json) ---"
          cat outdated.json
          echo "--------------------------------"

          # jq を使ってJSONファイルが空でないことを確認
          if [ $exit_code -eq 0 ] && jq -e 'keys | length > 0' outdated.json > /dev/null; then
            echo "Outdated packages found."
            echo "outdated=true" >> $GITHUB_OUTPUT
          else
            echo "No outdated packages."
            echo "outdated=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub issue body from file
        if: steps.outdated-check.outputs.outdated == 'true'
        run: |
          echo "| Package | Current Version | Latest Version |" > issue_body.md
          echo "|---------|-----------------|----------------|" >> issue_body.md
          cat outdated.json | jq -r 'to_entries | .[] | "| \(.key) | \(.value.current) | \(.value.latest) |"' >> issue_body.md

      - name: Create GitHub issue
        if: steps.outdated-check.outputs.outdated == 'true'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "新しいバージョンのパッケージに更新してください"
          content-filepath: ./issue_body.md
